# This will be set by the GitHub action to the folder containing this component.
ARG FOLDER=/app

FROM node:20-alpine AS base

# Enable corepack
ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0
RUN corepack enable

# Setup PNPM
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN mkdir -p /home/codespace/.pnpm-store /pnpm \
 && chown -R 1000:1000 /home/codespace/.pnpm-store /pnpm

# Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat

COPY . /app
WORKDIR ${FOLDER}

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
# ENV NEXT_TELEMETRY_DISABLED=1

USER 1000:1000

# Apply PNPM settings to be consistent with devcontainer
RUN pnpm config set node-linker hoisted --global \
 && pnpm config set store-dir /home/codespace/.pnpm-store --global

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["npm", "run", "dev"]
